### ISSUE TITLE
Bad Request when trying to populate json

### ISSUE THREAD

**Issue by idkjs** [itemsapi/starter#11]
##############################

macOS El Capitan, 10.11
Node 7.3 through nvm.
elasticsearch 1.7.3 through homebrew.
elesticsearch, redis and mongodb are running

###############################

When on /installation in running app,  I keep getting this bad request error whether following cli instructions of repo instructions. Here is the output from cli run. Any ideas on how to fix this? Thanks.

`klik@klik ~/P/M/i/items-gen-test (master)> env PORT=4000 npm start                         11:59:49

> itemsapi-starter@1.0.3 start /Users/klik/Projects/MongoDB-Projects/itemsapi/items-gen-test
> node app.js

  _ _                                 _ 
 (_) |_ ___ _ __ ___  ___  __ _ _ __ (_)
 | | __/ _ \ '_ ` _ \/ __|/ _` | '_ \| |
 | | ||  __/ | | | | \__ \ (_| | |_) | |
 |_|\__\___|_| |_| |_|___/\__,_| .__/|_|
                               |_|      
Ideas or issues - https://github.com/itemsapi/starter/issues

info: ItemsAPI started!
info: Elasticsearch status - OK
info: Open http://127.0.0.1:4000 in your browser to continue!
error:  Error: Bad Request
    at respond (/Users/klik/Projects/MongoDB-Projects/itemsapi/items-gen-test/node_modules/elasticsearch/src/lib/transport.js:293:15)
    at checkRespForFailure (/Users/klik/Projects/MongoDB-Projects/itemsapi/items-gen-test/node_modules/elasticsearch/src/lib/transport.js:252:7)
    at HttpConnector.<anonymous> (/Users/klik/Projects/MongoDB-Projects/itemsapi/items-gen-test/node_modules/elasticsearch/src/lib/connectors/http.js:155:7)
    at IncomingMessage.wrapper (/Users/klik/Projects/MongoDB-Projects/itemsapi/items-gen-test/node_modules/elasticsearch/node_modules/lodash/index.js:3095:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
error: { Error: Bad Request
    at respond (/Users/klik/Projects/MongoDB-Projects/itemsapi/items-gen-test/node_modules/elasticsearch/src/lib/transport.js:293:15)
    at checkRespForFailure (/Users/klik/Projects/MongoDB-Projects/itemsapi/items-gen-test/node_modules/elasticsearch/src/lib/transport.js:252:7)
    at HttpConnector.<anonymous> (/Users/klik/Projects/MongoDB-Projects/itemsapi/items-gen-test/node_modules/elasticsearch/src/lib/connectors/http.js:155:7)
    at IncomingMessage.wrapper (/Users/klik/Projects/MongoDB-Projects/itemsapi/items-gen-test/node_modules/elasticsearch/node_modules/lodash/index.js:3095:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
  status: 400,
  displayName: 'BadRequest',
  message: 'Bad Request' } 'Error: Bad Request\n    at respond (/Users/klik/Projects/MongoDB-Projects/itemsapi/items-gen-test/node_modules/elasticsearch/src/lib/transport.js:293:15)\n    at checkRespForFailure (/Users/klik/Projects/MongoDB-Projects/itemsapi/items-gen-test/node_modules/elasticsearch/src/lib/transport.js:252:7)\n    at HttpConnector.<anonymous> (/Users/klik/Projects/MongoDB-Projects/itemsapi/items-gen-test/node_modules/elasticsearch/src/lib/connectors/http.js:155:7)\n    at IncomingMessage.wrapper (/Users/klik/Projects/MongoDB-Projects/itemsapi/items-gen-test/node_modules/elasticsearch/node_modules/lodash/index.js:3095:19)\n    at emitNone (events.js:91:20)\n    at IncomingMessage.emit (events.js:185:7)\n    at endReadableNT (_stream_readable.js:974:12)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:122:9)'
error:  Error: Bad Request
    at respond (/Users/klik/Projects/MongoDB-Projects/itemsapi/items-gen-test/node_modules/elasticsearch/src/lib/transport.js:293:15)
    at checkRespForFailure (/Users/klik/Projects/MongoDB-Projects/itemsapi/items-gen-test/node_modules/elasticsearch/src/lib/transport.js:252:7)
    at HttpConnector.<anonymous> (/Users/klik/Projects/MongoDB-Projects/itemsapi/items-gen-test/node_modules/elasticsearch/src/lib/connectors/http.js:155:7)
    at IncomingMessage.wrapper (/Users/klik/Projects/MongoDB-Projects/itemsapi/items-gen-test/node_modules/elasticsearch/node_modules/lodash/index.js:3095:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
error: { Error: Bad Request
    at respond (/Users/klik/Projects/MongoDB-Projects/itemsapi/items-gen-test/node_modules/elasticsearch/src/lib/transport.js:293:15)
    at checkRespForFailure (/Users/klik/Projects/MongoDB-Projects/itemsapi/items-gen-test/node_modules/elasticsearch/src/lib/transport.js:252:7)
    at HttpConnector.<anonymous> (/Users/klik/Projects/MongoDB-Projects/itemsapi/items-gen-test/node_modules/elasticsearch/src/lib/connectors/http.js:155:7)
    at IncomingMessage.wrapper (/Users/klik/Projects/MongoDB-Projects/itemsapi/items-gen-test/node_modules/elasticsearch/node_modules/lodash/index.js:3095:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
  status: 400,
  displayName: 'BadRequest',
  message: 'Bad Request' } 'Error: Bad Request\n    at respond (/Users/klik/Projects/MongoDB-Projects/itemsapi/items-gen-test/node_modules/elasticsearch/src/lib/transport.js:293:15)\n    at checkRespForFailure (/Users/klik/Projects/MongoDB-Projects/itemsapi/items-gen-test/node_modules/elasticsearch/src/lib/transport.js:252:7)\n    at HttpConnector.<anonymous> (/Users/klik/Projects/MongoDB-Projects/itemsapi/items-gen-test/node_modules/elasticsearch/src/lib/connectors/http.js:155:7)\n    at IncomingMessage.wrapper (/Users/klik/Projects/MongoDB-Projects/itemsapi/items-gen-test/node_modules/elasticsearch/node_modules/lodash/index.js:3095:19)\n    at emitNone (events.js:91:20)\n    at IncomingMessage.emit (events.js:185:7)\n    at endReadableNT (_stream_readable.js:974:12)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:122:9)'
`

**Comment by cigolpl** [comment]
Hi Enso,

The `bad request` is on the elasticsearch side.
To fix it make sure:
- the data you upload is the valid JSON array
- the data is an array of flat objects (i.e. strings, arrays, numbers, location) but it cannot contain sub-objects / sub-items

By the way - have you tried the example with movies and if so, is it working ?

**Comment by idkjs** [comment]
@cigolpl i tried the movie example. By try, I mean that on the install page, the default json is the processed movies at <https://raw.githubusercontent.com/itemsapi/itemsapi-example-data/master/items/movies-processed.json>. I just clicked submit. If I go into mongodb. The collection is there but I only see the aggregation queries, not the actual movies. Output is ```> use itemsapi-starter
switched to db itemsapi-starter
> show collections
collections
configs
> db.collections.count();
8
> db.collections.findOne({})
{
	"_id" : ObjectId("5887d25e148e04570f8c59e5"),
	"name" : "miztguzf",
	"aggregations" : {
		"0" : {
			"title" : "0",
			"field" : "0",
			"conjunction" : true,
			"size" : 15,
			"type" : "terms"
		}
	},
	"normalSchema" : {
		"0" : {
			"store" : true,
			"index" : "not_analyzed",
			"display" : "array",
			"type" : "string"
		}
	},
	"updated_at" : ISODate("2017-01-24T22:17:02.588Z"),
	"created_at" : ISODate("2017-01-24T22:17:02.588Z"),
	"slugs" : [ ],
	"__v" : 0
}
> ```

**Comment by cigolpl** [comment]
That's interesting. In MongoDB you should have only `collection` but I see there are missed another fields in schema like rating, tags, actors etc. The data is stored in Elasticsearch.

You can try in CLI:
- `curl -XGET 'localhost:9200'`
- `curl localhost:9200/miztguzf`

We could know then if elasticsearch is storing the data properly.

Btw what is your mongodb version ? I usually use 3.0 or > 2.6

**Comment by idkjs** [comment]
mongo 3.4
```
klik@klik ~> curl -XGET 'localhost:9200'                                                   13:07:00
{
  "name" : "Fx3NAtx",
  "cluster_name" : "elasticsearch_klik",
  "cluster_uuid" : "tUbbUSWqTIGEAIKyPxhLpw",
  "version" : {
    "number" : "5.1.2",
    "build_hash" : "c8c4c16",
    "build_date" : "2017-01-11T20:18:39.146Z",
    "build_snapshot" : false,
    "lucene_version" : "6.3.0"
  },
  "tagline" : "You Know, for Search"
}
klik@klik ~> curl localhost:9200/miztguzf                                                  13:07:04
{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"miztguzf","index_uuid":"_na_","index":"miztguzf"}],"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"miztguzf","index_uuid":"_na_","index":"miztguzf"},"status":404}⏎                                        klik@klik ~> which mongo                                                                   13:07:13
/usr/local/bin/mongo
klik@klik ~> mongo version                                                                 13:07:34
MongoDB shell version v3.4.1
connecting to: mongodb://127.0.0.1:27017/version
MongoDB server version: 3.4.1
Server has startup warnings: 
2017-01-25T11:02:48.238+0100 I CONTROL  [initandlisten] 
2017-01-25T11:02:48.238+0100 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2017-01-25T11:02:48.238+0100 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2017-01-25T11:02:48.238+0100 I CONTROL  [initandlisten] 
2017-01-25T11:02:48.238+0100 I CONTROL  [initandlisten] 
2017-01-25T11:02:48.238+0100 I CONTROL  [initandlisten] ** WARNING: soft rlimits too low. Number of files is 256, should be at least 1000
> 

```

**Comment by cigolpl** [comment]
Cool, thanks!

1. the homebrew has installed the newest elasticsearch version somehow `5.1.2`. ItemsAPI is not fully supporting yet ES > 2.0. Let's try again with 1.7.x (this can be helpful https://github.com/itemsapi/itemsapi/blob/master/ELASTICSEARCH.md)

2. I am not sure if ItemsAPI works with MongoDB 3.4. If you fix elasticsearch version and still not working please consider downgrade'ing mongodb to 3.0

3. in some situation when you want to make installation again it's worth to delete mongodb collections to reset configuration.

**Comment by idkjs** [comment]
interesting because I already when through the steps in the link this morning. I unlinked elasticsearch then installed 1.7. Looks like its not unlinked/unlinking if this output is right...

```

klik@klik ~> brew search elasticsearch                                                     13:08:00
elasticsearch ✔                  elasticsearch@1.7 ✔              elasticsearch@2.4
klik@klik ~> brew unlink elasticsearch                                                     13:24:51
Unlinking /usr/local/Cellar/elasticsearch/5.1.2... 0 symlinks removed
klik@klik ~> brew search elasticsearch                                                     13:25:04
elasticsearch ✔                  elasticsearch@1.7 ✔              elasticsearch@2.4
klik@klik ~> brew search elasticsearch                                                     13:25:18
elasticsearch ✔                  elasticsearch@1.7 ✔              elasticsearch@2.4
klik@klik ~>    

```

**Comment by cigolpl** [comment]
@idkjs yeah that makes sense. seems something could be wrong with brew.

**Comment by idkjs** [comment]
@cigolpl what is your recommended way of installing it?

**Comment by cigolpl** [comment]
it's hard to say because I've not tested on mac. If you have some experience with docker then maybe it's worth to try because with docker you can run elasticsearch in one command i.e:

`docker run -d -p 127.0.0.1:9200:9200 elasticsearch:1.7.6`

**Comment by idkjs** [comment]
I will try docker. Incidentally, i get the same errors on heroku when using these instructions: <https://www.itemsapi.com/docs/tutorials/search-backend-for-restaurants-itemsapi-elasticsearch-nodejs>

```
2017-01-25T11:26:23.245322+00:00 app[web.1]:   toJSON: [Function] } 'Error: [parse_exception] Failed to derive xcontent\n    at respond (/app/node_modules/elasticsearch/src/lib/transport.js:293:15)\n    at checkRespForFailure (/app/node_modules/elasticsearch/src/lib/transport.js:252:7)\n    at HttpConnector.<anonymous> (/app/node_modules/elasticsearch/src/lib/connectors/http.js:155:7)\n    at IncomingMessage.wrapper (/app/node_modules/elasticsearch/node_modules/lodash/index.js:3095:19)\n    at emitNone (events.js:91:20)\n    at IncomingMessage.emit (events.js:185:7)\n    at endReadableNT (_stream_readable.js:974:12)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:122:9)'
```

**Comment by cigolpl** [comment]
There are many new features since the tutorials creation and they might be not up to date. Sorry for that. I hope I'll create some new tutorial soon. Thanks for your feedback!

**Comment by idkjs** [comment]
@cigolpl i dont mind reading through the code and making changes if necessary. Where do you suggest I start for the best working version.

**Comment by cigolpl** [comment]
@idkjs I suggest start using itemsapi starter on your localhost with your best IDE.
Elasticsearch, Redis and Mongo could be anywhere, where is the most convenient for you. Sometimes I even use digitalocean for that because I can create new machine with docker, ubuntu, etc, pay per hours and make a snapshot when I stop using.

**Comment by idkjs** [comment]
@cigolpl thanks for the guidance. Great project. Happy to help in anyway I can. Do you have any immediate needs?

**Comment by cigolpl** [comment]
@idkjs the small improvements are very welcome, depends where you feel best and what you like to do.

From my perspective:
- there are many ways for improvement in the main layout
- there are plans for new tutorials because there are new things and the current ones are quite old
- the feedback and advices from the UI standpoint (i.e. how to simplify the creation of application) are always very welcome

**Comment by idkjs** [comment]
@cigolpl im going to try to get a working version of this thing going, then I will jump in to your list. If you have a working docker image you dont mind sharing, please let me know so I dont go figure this out.

**Comment by cigolpl** [comment]
@idkjs unfortunately I don't have very good working docker version but there is a plan to make working docker compose which create the whole environment easily.

**Comment by idkjs** [comment]
Keep up the good work, sir. Thanks for talking.

**Comment by cigolpl** [comment]
Thanks also. You are welcome!

**Comment by bjarman** [comment]
Hi! I am stuck during installation with "Bad request" trying to import the movies-processed.json.

Did this issue get resolved and if so what do I need to do to get past this bump?

Thanks!

**Comment by cigolpl** [comment]
Hello @bjarman, please ensure you are using Elasticsearch 1.5.x or 1.7.x

**Comment by bjarman** [comment]
My elastic looks like tihs:
{
  "name" : "stFUyIP",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "8C3V_kyBTLG-jpot90P4qQ",
  "version" : {
    "number" : "5.4.1",
    "build_hash" : "2cfe0df",
    "build_date" : "2017-05-29T16:05:51.443Z",
    "build_snapshot" : false,
    "lucene_version" : "6.5.1"
  },
  "tagline" : "You Know, for Search"
}
And my mongod looks like this: version v3.4.5

Wrong versions?

**Comment by cigolpl** [comment]
Yeah, unfortunately 5.4.1 version is not supported now.. Also not sure if mongodb v3.4.5 will be working properly. My suggestion is to downgrade them or use docker compose (https://www.itemsapi.com/docs/starter/installation/)

**Comment by bjarman** [comment]
Ok, thank you!
