### ISSUE TITLE
Initially adding the collection - getting 405 MethodNotAllowed

### ISSUE THREAD

**Issue by k-sudhan** [itemsapi/starter#23]
Getting following error when I try to load the data through "/installation" page and using the default movies-processed.json file.

` error:  Error: Incorrect HTTP method for uri [/wgptgaib] and method [POST], allowed: [GET, PUT, HEAD, DELETE]
2018-01-18T21:48:30.749848+00:00 app[web.1]:     at respond (/app/node_modules/itemsapi/node_modules/elasticsearch/src/lib/transport.js:293:15)
2018-01-18T21:48:30.749849+00:00 app[web.1]:     at checkRespForFailure (/app/node_modules/itemsapi/node_modules/elasticsearch/src/lib/transport.js:252:7)
2018-01-18T21:48:30.749851+00:00 app[web.1]:     at HttpConnector.<anonymous> (/app/node_modules/itemsapi/node_modules/elasticsearch/src/lib/connectors/http.js:155:7)
2018-01-18T21:48:30.749852+00:00 app[web.1]:     at IncomingMessage.wrapper (/app/node_modules/itemsapi/node_modules/lodash/index.js:3095:19)
2018-01-18T21:48:30.749854+00:00 app[web.1]:     at emitNone (events.js:111:20)
2018-01-18T21:48:30.749855+00:00 app[web.1]:     at IncomingMessage.emit (events.js:208:7)
2018-01-18T21:48:30.749856+00:00 app[web.1]:     at endReadableNT (_stream_readable.js:1055:12)
2018-01-18T21:48:30.749857+00:00 app[web.1]:     at _combinedTickCallback (internal/process/next_tick.js:138:11)
2018-01-18T21:48:30.749859+00:00 app[web.1]:     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
2018-01-18T21:48:30.756004+00:00 app[web.1]: error: { Error: Incorrect HTTP method for uri [/wgptgaib] and method [POST], allowed: [GET, PUT, HEAD, DELETE]
2018-01-18T21:48:30.756007+00:00 app[web.1]:     at respond (/app/node_modules/itemsapi/node_modules/elasticsearch/src/lib/transport.js:293:15)
2018-01-18T21:48:30.756008+00:00 app[web.1]:     at checkRespForFailure (/app/node_modules/itemsapi/node_modules/elasticsearch/src/lib/transport.js:252:7)
2018-01-18T21:48:30.756009+00:00 app[web.1]:     at HttpConnector.<anonymous> (/app/node_modules/itemsapi/node_modules/elasticsearch/src/lib/connectors/http.js:155:7)
2018-01-18T21:48:30.756010+00:00 app[web.1]:     at IncomingMessage.wrapper (/app/node_modules/itemsapi/node_modules/lodash/index.js:3095:19)
2018-01-18T21:48:30.756011+00:00 app[web.1]:     at emitNone (events.js:111:20)
2018-01-18T21:48:30.756017+00:00 app[web.1]:     at IncomingMessage.emit (events.js:208:7)
2018-01-18T21:48:30.756018+00:00 app[web.1]:     at endReadableNT (_stream_readable.js:1055:12)
2018-01-18T21:48:30.756019+00:00 app[web.1]:     at _combinedTickCallback (internal/process/next_tick.js:138:11)
2018-01-18T21:48:30.756020+00:00 app[web.1]:     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
2018-01-18T21:48:30.756021+00:00 app[web.1]:   status: 405,
2018-01-18T21:48:30.756022+00:00 app[web.1]:   displayName: 'MethodNotAllowed',
2018-01-18T21:48:30.756025+00:00 app[web.1]:   message: 'Incorrect HTTP method for uri [/wgptgaib] and method [POST], allowed: [GET, PUT, HEAD, DELETE]' } 'Error: Incorrect HTTP method for uri [/wgptgaib] and method [POST], allowed: [GET, PUT, HEAD, DELETE]\n `

**Comment by cigolpl** [comment]
Hello, what is your Elasticsearch version ? From my experience this app was working only with 1.x and 2.x

**Comment by k-sudhan** [comment]
I am trying to use it on heroku platform.  It defaults it to ES 6.0.1 version (no matter if the app.json has 1.7 version set).  Is there any workaround or other option if I have to run it on Heroku ?  Thank you for creating such a robust application.

**Comment by cigolpl** [comment]
Thanks for kind words! It seems indeed bonsai is not supporting ES 1.7 now https://docs.bonsai.io/v1.0/docs/supported-elasticsearch-versions :( I don't have any quick idea now how to fix it simply. There is also another ES provide on heroku (https://elements.heroku.com/addons/searchbox) but not sure if they supports ES 1.7

**Comment by k-sudhan** [comment]
Thanks !!!
I will give it a try and let you know.

**Comment by k-sudhan** [comment]
@cigolpl  Thanks for all your help. SearchBox worked for me. I had to explicitly specify the version, else it was taking the latest version by default.
